import React from 'react';
import { Link } from 'react-router-dom';
import { ErrorBlock, LoadingBlock } from '../components/StateBlocks.jsx';
import { useApiResource } from '../hooks/useApiResource.js';
import MentorReview from '../features/profile/MentorReview.jsx';
import PublicProfileControls from '../features/profile/PublicProfileControls.jsx';

export default function CareerProfile() {
  const { data, loading, error, refetch } = useApiResource('/dashboard');
  if (loading && !data) return <LoadingBlock label="Loading your career profile" className="min-h-dvh" />;
  if (error && !data) return <div className="p-6 pt-16 lg:pt-6"><ErrorBlock error={error} onRetry={refetch} /></div>;
  const missingResume = data.resume.checks.filter((check) => !check.passed);
  const verified = data.skills.filter((skill) => skill.verified).length;
  return <div className="bg-background text-on-surface min-h-dvh"><div className="max-w-5xl mx-auto px-5 md:px-8 pt-16 lg:pt-6 pb-10 space-y-4"><header><p className="text-xs font-bold uppercase tracking-[0.2em] text-primary">Your professional evidence</p><h1 className="font-headline text-2xl md:text-3xl font-black tracking-tight mt-1">Profile & resume</h1><p className="text-sm text-on-surface-variant mt-1">Maintain one source of truth, then tailor a resume for each opportunity.</p></header><div className="grid grid-cols-1 md:grid-cols-3 gap-3"><Link to="/profile" className="rounded-xl border border-outline-variant/60 bg-surface-container-lowest p-5 hover:border-primary/40"><span className="material-symbols-outlined text-primary">person</span><h2 className="font-bold mt-2">Career profile</h2><p className="text-sm text-on-surface-variant mt-1">Education, projects, experience, certificates and professional links</p></Link><Link to="/resume-builder" className="rounded-xl border border-outline-variant/60 bg-surface-container-lowest p-5 hover:border-primary/40"><span className="material-symbols-outlined text-primary">description</span><h2 className="font-bold mt-2">Resume versions</h2><p className="text-sm text-on-surface-variant mt-1">ATS score {data.resume.atsScore}; {missingResume.length} improvements remain</p></Link><Link to="/documents" className="rounded-xl border border-outline-variant/60 bg-surface-container-lowest p-5 hover:border-primary/40"><span className="material-symbols-outlined text-primary">folder</span><h2 className="font-bold mt-2">Placement documents</h2><p className="text-sm text-on-surface-variant mt-1">Keep verified documents ready before a deadline.</p></Link></div><section className="rounded-xl border border-outline-variant/60 bg-surface-container-lowest p-5"><div className="flex justify-between gap-3"><div><h2 className="font-bold">Skills & proof</h2><p className="text-sm text-on-surface-variant">{verified} of {data.skills.length} listed skills are verified.</p></div><Link to="/skills" className="text-sm font-bold text-primary hover:underline">Manage and assess</Link></div><div className="flex flex-wrap gap-2 mt-4">{data.skills.map((skill) => <span key={skill._id} className={`px-3 py-1.5 rounded-full text-xs font-bold ${skill.verified ? 'bg-green-100 text-green-800' : 'bg-surface-container text-on-surface-variant'}`}>{skill.verified ? '✓ ' : ''}{skill.name}</span>)}</div></section>{missingResume.length > 0 && <section className="rounded-xl border border-outline-variant/60 bg-surface-container-lowest p-5"><h2 className="font-bold">Improve before your next application</h2><ul className="mt-3 space-y-2">{missingResume.slice(0, 4).map((check) => <li key={check.label} className="flex gap-2 text-sm"><span className="material-symbols-outlined text-base text-primary">arrow_right</span>{check.label}</li>)}</ul></section>}<PublicProfileControls /><MentorReview /></div></div>;
}
