import React from 'react';
import { Link } from 'react-router-dom';
import { ErrorBlock, LoadingBlock } from '../components/StateBlocks.jsx';
import { useApiResource } from '../hooks/useApiResource.js';

export default function Updates() {
  const calendar = useApiResource('/calendar/me');
  const inbox = useApiResource('/announcements/me');
  const dashboard = useApiResource('/dashboard');
  if (calendar.loading && !calendar.data) return <LoadingBlock label="Loading your updates" className="min-h-dvh" />;
  if (calendar.error && !calendar.data) return <div className="p-6 pt-16 lg:pt-6"><ErrorBlock error={calendar.error} onRetry={calendar.refetch} /></div>;
  const messages = inbox.data?.announcements ?? [];
  const notices = dashboard.data?.notifications ?? [];
  return <div className="bg-background text-on-surface min-h-dvh"><div className="max-w-5xl mx-auto px-5 md:px-8 pt-16 lg:pt-6 pb-10 space-y-4"><header><p className="text-xs font-bold uppercase tracking-[0.2em] text-primary">Deadlines and communication</p><h1 className="font-headline text-2xl md:text-3xl font-black tracking-tight mt-1">Updates</h1><p className="text-sm text-on-surface-variant mt-1">Everything that needs your attention, in one place.</p></header>{calendar.data?.next && <section className="rounded-xl bg-inverse-surface text-white p-5"><p className="text-[10px] font-black uppercase tracking-[0.18em] opacity-70">Next on your calendar</p><h2 className="font-headline text-lg font-black mt-1">{calendar.data.next.title}</h2><p className="text-sm opacity-75 mt-1">{new Date(calendar.data.next.startsAt).toLocaleString('en-IN')}{calendar.data.next.venue ? ` · ${calendar.data.next.venue}` : ''}</p><Link to="/calendar" className="inline-flex mt-3 text-sm font-bold underline">Open calendar</Link></section>}<div className="grid grid-cols-1 lg:grid-cols-2 gap-4"><section className="rounded-xl border border-outline-variant/60 bg-surface-container-lowest p-5"><div className="flex justify-between"><h2 className="font-bold">Required actions</h2><span className="text-xs font-black">{notices.length}</span></div><ul className="mt-3 space-y-2">{notices.slice(0, 5).map((notice) => <li key={notice.id}><Link to={notice.action.to} className="flex gap-3 p-3 rounded-lg bg-surface-container-low hover:bg-surface-container"><span className="material-symbols-outlined text-primary">{notice.icon}</span><div><p className="text-sm font-bold">{notice.title}</p><p className="text-xs text-on-surface-variant mt-0.5">{notice.body}</p></div></Link></li>)}{notices.length === 0 && <li className="text-sm text-on-surface-variant">Nothing requires action right now.</li>}</ul></section><section className="rounded-xl border border-outline-variant/60 bg-surface-container-lowest p-5"><div className="flex justify-between"><h2 className="font-bold">Placement office messages</h2><span className="text-xs font-black">{inbox.data?.unread ?? 0} unread</span></div><ul className="mt-3 space-y-2">{messages.slice(0, 5).map((message) => <li key={message._id} className="p-3 rounded-lg bg-surface-container-low"><p className="text-sm font-bold truncate">{message.subject}</p><p className="text-xs text-on-surface-variant mt-0.5">{message.from} · {new Date(message.sentAt).toLocaleDateString('en-IN')}</p></li>)}{messages.length === 0 && <li className="text-sm text-on-surface-variant">No messages yet.</li>}</ul><Link to="/inbox" className="inline-flex mt-3 text-sm font-bold text-primary hover:underline">Open all messages</Link></section></div></div></div>;
}
