import { Router } from 'express';
import { adminRoutes } from './admin.routes.js';
import { authRoutes } from './auth.routes.js';
import { calendarRoutes } from './calendar.routes.js';
import { companyRoutes } from './company.routes.js';
import { driveRoutes } from './drive.routes.js';
import { jobRoutes } from './job.routes.js';
import { matchRoutes } from './match.routes.js';
import { offerRoutes } from './offer.routes.js';
import { recruiterRoutes } from './recruiter.routes.js';
import { skillAssessmentRoutes } from './skillAssessment.routes.js';
import { dashboardRoutes } from './dashboard.routes.js';
import { interviewRoutes } from './interview.routes.js';
import { problemRoutes } from './problem.routes.js';
import { profileRoutes } from './profile.routes.js';
import { questionRoutes } from './question.routes.js';
import { resumeRoutes } from './resume.routes.js';
import { testRoutes } from './test.routes.js';

export const routes = Router();

routes.use('/auth', authRoutes);
routes.use('/profile', profileRoutes);
routes.use('/problems', problemRoutes);
routes.use('/questions', questionRoutes);
routes.use('/tests', testRoutes);
routes.use('/interviews', interviewRoutes);
routes.use('/resumes', resumeRoutes);
routes.use('/dashboard', dashboardRoutes);
routes.use('/companies', companyRoutes);
routes.use('/match', matchRoutes);
routes.use('/jobs', jobRoutes);
routes.use('/drives', driveRoutes);
routes.use('/offers', offerRoutes);
routes.use('/calendar', calendarRoutes);
routes.use('/recruiters', recruiterRoutes);
routes.use('/skills', skillAssessmentRoutes);
routes.use('/admin', adminRoutes);
